name: lp

epochs: 50
lr: 0.001
weight_decay: 1e-5
batch_size: 2048
num_neighbors: [15, 5, 5]
num_train_neg: 1
inference_batch_size: 4096
eval_preload_node_emb: true
eval_every: 1
patience: 20
max_train_batches: null
eval_edge_batch_size: 2048

loss:
  aux_weight: 1.0

decoder:
  name: mlp
  hidden_dim: 256
  num_layers: 3
  dropout: 0.02
