name: nc

epochs: 100
lr: 5e-3
weight_decay: 1e-5
batch_size: 1024
num_neighbors: 15
inference_mode: full
inference_batch_size: 4096
eval_every: 1
patience: 20
max_train_batches: null

loss:
  aux_weight: 1.0
