name: nc

epochs: 100
lr: 5e-3
weight_decay: 1e-5
batch_size: 1024
num_neighbors: [15, 15]
inference_batch_size: 4096
eval_every: 1
eval_test_each_epoch: false
test_on_best: true
patience: 30
selection_metric: acc
max_train_batches: null

loss:
  aux_weight: 1.0

metrics:
  - acc
  - macro_f1
